name: API Documentation Validation and Deployment

on:
  pull_request:
    paths:
      - 'docs/**'
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  build-and-deploy:
    uses: decentraland/platform-actions/.github/workflows/apps-docs.yml@main
    with:
      path-to-docs: 'docs/comms-gatekeeper-openapi.yaml'
      path-to-output: 'docs/index.html'
      node-version: '20'
