name: API Documentation Validation and Deployment

on:
  pull_request:
    paths:
      - 'docs/**'
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  build-and-deploy:
    uses: decentraland/platform-actions/.github/workflows/apps-docs.yml@feat/bundle-docs-into-one-api-reference-file
    with:
      api-spec-file: 'docs/comms-gatekeeper-openapi.yaml'
      output-file: 'docs/index.html'
      output-directory: './docs'
      node-version: '20'
