name: API Documentation Validation and Deployment

on:
  pull_request:
    paths:
      - 'docs/**'
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  build-and-deploy:
    uses: decentraland/platform-actions/.github/workflows/apps-docs.yml@refactor/rename-docs-workflow-inputs
    with:
      path-to-api-spec: 'docs/comms-gatekeeper-openapi.yaml'
      path-to-docs: './docs'
      node-version: '20'
