name: API Documentation Validation and Deployment

on:
  pull_request:
    paths:
      - 'docs/**'
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  build-and-deploy:
    uses: decentraland/platform-actions/.github/workflows/apps-docs.yml@fix/publish-to-gitbook
    with:
      api-spec-file: 'docs/openapi.yaml'
      api-spec-name: 'comms-gatekeeper-api'
      output-directory: './docs'
      output-bundle-file: 'docs/api-reference.yaml'
      node-version: '20'
    secrets: inherit
